export const language = {
  en: {
    general: {
      saved_words: 'Saved words',
      english: 'English',
      vietnamese: 'Vietnamese',
      full_text: 'Full Text',
      summarized_text: 'Summarized Text',
      search: 'Search',
      save_word: 'Save word',
      saved: 'Saved',
      most_common_meaning: 'Most common meaning',
      synonyms: 'Synonyms',
      translate: 'Translate',
      writing_assistant: 'Writing assistant',
      submit: 'Submit',
      skip_it: 'Skip it',
    },
    dashboard: {
      welcome: 'Welcome to Macaw',
      instruction: 'Please type in the word you are looking for',
      email: 'Please enter your email so we can support you better',
      back_to_dashboard: 'Back to dashboard',
    },
    popup: {
      check_saved_words: 'Check saved words',
      word_limit: 'Over 100 words limit',
    },
    err: {
      title: 'Oops, something went wrong.',
      limit_word: 'You have reached our word limit (100 words)',
      meaning_word: 'We could not find the meaning of this word',
    },
    writing_popup: {
      tone: 'Tone',
      intention: 'Intention',
      apply: 'Apply',
      restore: 'Cancel',
      tones: {
        formal: 'Formal',
        optimistic: 'Optimistic',
        confident: 'Confident',
      },
      intents: {
        formal: 'Formal',
        informal: 'Informal',
        command: 'Command',
        convince: 'Convince',
        storytelling: 'Storytelling',
        strong: 'Strong',
        humorous: 'Humorous',
      },
    },
  },
  vi: {
    general: {
      saved_words: 'Từ đã lưu',
      english: 'Tiếng Anh',
      vietnamese: 'Tiếng Việt',
      full_text: 'Văn bản gốc',
      summarized_text: 'Bản tóm tắt',
      search: 'Tìm',
      save_word: 'Lưu từ',
      saved: 'Đã lưu',
      most_common_meaning: 'Nghĩa thông dụng nhất',
      synonyms: 'Từ đồng nghĩa',
      translate: 'Dịch',
      writing_assistant: 'Hỗ trợ viết',
      submit: 'Gửi',
      skip_it: 'Bỏ qua',
    },
    dashboard: {
      welcome: 'Chào mừng đến Macaw',
      instruction: 'Gõ từ hoặc câu bạn cần dịch bên dưới',
      email: 'Vui lòng nhập email để tụi mình phục vụ bạn tốt hơn',
      back_to_dashboard: 'Trở về trang chủ',
    },
    popup: {
      check_saved_words: 'Xem từ đã lưu',
      word_limit: 'Vượt 100 từ giới hạn',
    },
    err: {
      title: 'Ui, đã có lỗi xảy ra.',
      limit_word: 'Bạn đạt vượt quá giới hạn từ dịch (100 từ)',
      meaning_word: 'Tụi mình không tìm được nghĩa của từ này',
    },
    writing_popup: {
      tone: 'Giọng văn',
      intention: 'Mục đích',
      apply: 'Áp dụng',
      restore: 'Phục hồi',
      tones: {
        formal: 'Trang trọng',
        optimistic: 'Lạc quan',
        confident: 'Tự tin',
      },
      intents: {
        formal: 'Trang trọng',
        informal: 'Thông thường',
        command: 'Yêu cầu',
        convince: 'Thuyết phục',
        storytelling: 'Kể chuyện',
        strong: 'Mạnh mẽ',
        humorous: 'Hài hước',
      },
    },
  },
};
